<!-- Page de présentation du jeu -->
<h2><i class="fas fa-scroll"></i> About BDO</h2>

<!--  PAGE ABOUT BDO -->
<div id="aboutBdo">	
	<ol class="aboutBdo">
		<li>
			<h3>INTRO: MAP, REGIONS AND CITIES</h3>
			<ol>
				<li>
					<h4>The world of BDO</h4>
					<p class="world" >Black Desert Online is a vast living and immersive world, waiting for you to explore and unveil its secrets. We will quickly examine the areas you can visit and some of the unique features of each of them and their cities. Join us and participate in the defense of this world to regions invaded by gloomy monsters or wars of territorial conquest! </p>
					<img src="img/regions/world.png" alt="bdo map size" >
				</li>
				<li>
					<h4>VARIOUS AND VARIED REGIONS AND THEIR CAPITALS</h4>
					<ol>
						<li>
							<h5>Balenos</h5>
							<img src="img/regions/balenos.png" alt="balenos area" >
							<ul>
								<li>Capital : Velia</li>
								<li>Main city : Olvia</li>
								<li>Climate : Subtropical Humid</li>
							</ul>
							<p>Starting area of the game, Balenos is nestled north of Serendia, along the coast. This peaceful area is famous for the generous fishing near the capital, Velia, but the whole region is renowned for its abundant resources such as horses, crops and timber. </p>
						</li>
						<li>
							<h5>Serendia</h5>
							<img src="img/regions/serendia.png" alt="serendia area" >
							<ul>
								<li>Capital : Heidel</li>
								<li>Main city : Glish</li>
								<li>Climate : Mild</li>
							</ul>
							<p>Serendia is home to many of the best craftsmen in the world, most of whom live in Heidel. In the past, there was great animosity between Calpheon and Serendia, but since the return of the Serendia king, the tensions have faded. </p>
						</li>
						<li>
							<h5>Calpheon</h5>
							<img src="img/regions/calpheon.png" alt="calpheon area" >
							<ul>
								<li>Capital : Calpheon</li>
								<li>Major cities : Keplan, Trent, Epheria Port</li>
								<li>Climate : Subtropical / Temperate Humid</li>
							</ul>
							<p>The Calpheon area is home to the Republic of Calpheon, backed by his subjects, Serendia & Balenos. Located in the far west, Calpheon has few natural resources, apart from timber, but its insufficient resources are largely offset by dangerous dungeons. </p>
						</li>
						<li>
							<h5>Mediah</h5>
							<img src="img/regions/mediah.png" alt="mediah area" >
							<ul>
								<li>Capital : Altinova</li>
								<li>Main city : Tarif</li>
								<li>Climate : Dry meadows</li>
							</ul>
							<p>Located between Serendia and Valencia, Mediah is an arid and arid landscape serving as a gateway to the Valencian desert. With the recent surge in travel in the region, the capital, Altinova, has seen a dramatic increase in trade, breathing new life into the region.</p>
						</li>
						<li>
							<h5>Valencia</h5>
							<img src="img/regions/valencia.png" alt="desert area" >
							<ul>
								<li>Capital : Valence Ville</li>
								<li>Major cities :  Valencia, Shakatu</li>
								<li>Climate : Desert</li>
							</ul>
							<p>Enclosed in a violent conflict with the Republic of Calpheon since always, Valencia is a huge desert, carrying the pride of the nation, the city of Valencia. The original discoverers of black stones, the people of Valencia work tirelessly to collect as many black stones as possible in the war effort against Calpheon. </p>
						</li>
						<li>
							<h5>Margoria</h5>
							<img src="img/regions/margoria.png" alt="north sea area" >
							<ul>
								<li>Capital : Port Ratt</li>
								<li>Main city :  Port Ratt</li>
								<li>Climate : Oceanic</li>
								<li>Resources specific to the marine region: starfish, sea anemones</li>
							</ul>
							<p>Lost far from the sea, Haso Kingdom is home to Magoria. Although it is known to be the birthplace of the greatest martial artists, the rest of the region is shrouded in mystery. Adventurers recently traveled to Port Ratt in hopes of learning more about the area.</p>
						</li>
						<li>
							<h5>Drieghan</h5>
							<img src="img/regions/drieghan.jpg" alt="south of bdo world" >
							<ul>
								<li>Capital : Duvencrune</li>
								<li>Main city :  Duvencrune</li>
								<li>Climate : Mountaign</li>
								<li>Specific resources, mountainous region: ferns, Thuja trees, meat and skin of Yak as well as Lama</li>
							</ul>
							<p>Drieghan, also known as the country of the dragons, is a mountainous landlocked territory. It is bordered by Serendia to the north, Mediah to the northeast, Kamasylvia to the west and Calpheon to the northwest. It is said to be a country of high peaks and long valleys with dragons.</p>
						</li>
					</ol>
				</li>
			</ol>
		</li>
		<li>
			<h3>FEATURES OF BLACK DESERT ONLINE</h3>
			<ol>
				<li>
					<h4>FARMING</h4>
					<p>Unlike some MMORPGs, BDO focuses on the farm which involves spending a lot of time fighting monsters invading areas in various parts of the world map of the game. You'll notice that depending on the level of these "mobs" (monsters) we will gain experience gain to reach the next levels for a stronger character, more agile with more skills to unlock ..</p>
				</li>
				<li>
					<h4>FISHING</h4>
					<p>Nothing more amazing than the number of things to do in BDO that require a proper internet connection! The afk that we can become makes this game all the more attractive. Reach a level sufficient to catch a max of fish (common or rare) then dry them to put them in boxes by tones and later to acquire a big sum when shopping at the other end of the world is common practice!</p>
				</li>
				<li>
					<h4>TAMING</h4>
					<p>Become a top breeder, an outstanding trainer, nothing more effective in BDO! Here is the picture of the types of horses that can be obtained through the mating of all wild horses available in the wild. Let's grab them and swap them if they can not have foals anymore. From tier 3 to tier 8, up to several attempts to awaken our best horse to win one of 3 dreamlike horses.</p>
					<img src="img/lifeskills/AllHorsesbyBreed.jpg" class="horses" alt="taming and breeding horses">
				</li>
				<li>
					<h4>TIER 9 DREAMLIKE HORSES</h4>
					<p>There are 3 dream horses: the Arduanatt pegaze, the Diné unicorn and the Doom horse of hell and there is only 1 percent chance of success of awakening your horse tier 8 to tier 9, good luck! Each of them own faculties, one can fly, the other run in the desert, but many other things ..</p>
					<img src="img/lifeskills/3tier9.jpg" alt="awakened horses">
				</li>
			</ol>
		</li>
		<li>
			<h3>GENERALITIES OF MMORPG</h3>
			<ol>
				<li>
					<h4>METHOD OF OPTIMIZING EQUIPMENT</h4>
					<p>Some people will take a close look at this way of trying to improve their equipment and weapons of all kinds. BDO rests if we can say on the RNG, that is to say any number generated, which according to the value, so, randomly obtained will validate the optimization or revera false (which will give us an accumulation of failures for a better success rate for the next try). Nothing more eloquent than a video youtube test to move to the next level of advanced equipment here.</p>
					<iframe width="560" height="315" src="https://www.youtube.com/embed/rBIR-AteCys" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
				</li>
				<li>
					<h4>Market Place</h4>
					<p>BDO has a central market, allowing us to place orders at average prices based on the value of the item at the moment. We can of course also buy if we have the means, all items put on sale, so provided that there is stock.</p>
					<img src="img/market/bdo-central-market-guide.png" alt="market place banner">
					<p>All servers in the game are connected to the same market, all EU servers to the EU market, but not US .. There are still any kind of materials, tools, food on sale at will to manufacture , or cook to sell. I'll let you discover all the sections of the market and its many elements, so there are things to do in this game.</p>
					
				</li>
				<li>
					<h4>INCREASE IN-GAME FUNDS</h4>
					<p>If you wish, you can increase your in-game silvers funds to buy what you need, namely tools, weapons and armor (there are 3 levels for those: green, blue and yellow) that are not not at all easily optimizable, so to buy! But you can also resell an object just optimized. Sometimes we are lucky with us, and we can turn an item of millions of silvers into 1, 2 or 5 or 8 or 10 billion silvers! There are many methods to make money: loots (object left on the ground, loot) of monsters / bosses, quest rewards, resale and all the possibilities offered by the use of lifeskills "professions ".</p>
				</li>
				<li>
					<h4>THE DIFFERENT PROFESSIONS</h4>
					<ol>
						<li>
							<h5>THE SPECIAL: THE PROCESSING</h5>
							<p>We will first talk about this profession. Indeed, it includes certain predispositions of each character to modify, create or combine something from raw materials and minerals.</p>
							<img src="img/market/processing.jpg" class="process" alt="processing character functions">
							<p>You can shake, heat, crush, cut wood, dry, cook, refine and cook different items bought on the market or harvested by your own workers!</p>
						</li>
						<li>
							<h5>OTHERS: FARMER, BROWSER ETC.</h5>
							<p>All the professions available in BDO are as follows, I leave you to your imagination when your hero will undertake: outings alone or with several, making tons of beer, elixirs or dishes, manual harvesting sap, logs, etc.. </p>
							<img src="img/market/lifeskills.png" class="lifeskills" alt="all lifeskills character levels">
						</li>
					</ol>
				</li>
			</ol>
		</li>
		<li>
			<h3>WORLD BOSSES AND LEVELING</h3>
			<ol>
				<li>
					<h4>Kzarka</h4>
					<img src="img/bdo-kzarka-boss.png" alt="Kzarka world boss">
					<p>This is your first "world boss"! Almost the best weapon of the game, from time to time we loot a box of weapon according to the boss fought. Still the RNG! It will take patience to collect all! Because indeed, there are 3 types of different weapons: primary weapon, the secondary one and the weapon of enlightenment. To summarize, the points of attack of the secondary weapon add up with those of the other two weapons. There are other weapons and armor to collect around the world of BDO, so many other bosses! Good luck to everyone.</p>
					<img src="img/market/kzarka-loot.png" class="kzarkaloot" alt="Kzarka world boss possible loot">
				</li>
				<li>
					<h4>FROM LEVEL 1 TO LEVEL 60 (68 MAX)</h4>
					<p>BDO twitter said: "Khviftwqtz is the first to reach level 65 in the EU region, all of us at Kakao Games USA and Kakao Games Europe". While I'm trying to reach level 63 (not bad at all: o]). You have just installed the game? Ever dreamed of playing an archer? Then Archer's character class is for you. A crossbow on the left arm (primary weapon), a raghon glove on the right arm (secondary weapon) and a large bow (awakened weapon) will do you the greatest good. Just continue the quests to upgrade your hero from level 3 to level 50. At 56, you can use your waking weapon! and yes for the other character classes, but with Archer, we can equip it right away and use it! Otherwise, you only have to follow the level of the monsters from one discovery zone to another to get your hero up (also farming, staying fight the same mobs).</p>
					<img src="img/regions/leveling.jpg" alt="level 3 to 50 quickly">
				</li>
			</ol>
		</li>
		<li>
			<h3>THE DIFFERENT CHARACTER CLASSES</h3>
			<p>There are 16 character classes in BDO: </p>			
			<table class="allclasses">
				<tr>
					<td>
						<a rel="classdesc" title="The Furious Fists combat style combines both classic martial arts and harsher techniques made popular by street fights.<br><br><img src='img/classes/striker_diag.png' style='box-shadow: none' />"> <img src="img/classes/striker.png" alt="striker"></a>
					</td>
				</tr>
                <tr>
                    <td>
                        <a rel="classdesc" title="The Mystic combat style is the same as Striker and has many complex combos that can deal damage over time whilst keeping their target locked down.<br><br><img src='img/classes/mystic_diag.png' style='box-shadow: none' />"> <img src="img/classes/mystic.png" alt="mystic"></a>
					</td>
                </tr>
				<tr>
					<td>
                        <a rel="classdesc" title="Burn, ice and break your enemies with the power of the natural elements to win the supreme victory.<br><br><img src='img/classes/wizard_diag.png' style='box-shadow: none' />"><img src="img/classes/wizard.png" alt="wizard" id="wizard"></a>
                    </td>
                </tr>
				<tr>
                    <td>
                        <a rel="classdesc" title="Defeat your enemies with the power of the 2 others natural elements: electricity and earth!.<br><br><img src='img/classes/witch_diag.png' style='box-shadow: none' />"><img src="img/classes/witch.png" alt="witch"></a>
					</td>
				</tr>
				<tr>
					<td>
                        <a rel="classdesc" title="The Ninja is an effective close-combat class, able to roam the terrain in the blink of an eye and murder their enemies.<br><br><img src='img/classes/ninja_diag.png' style='box-shadow: none' />"><img src="img/classes/ninja.png" alt="ninja" id="ninja"></a>
                    </td>
                </tr>
                <tr>
					<td>
                        <a rel="classdesc" title="The Kunoichis specialize in deflecting attacks to make perfect parries before making devastating counter-attacks.<br><br><img src='img/classes/kunoichi_diag.png' style='box-shadow: none' />"><img src="img/classes/kunoichi.png" alt="kunoichi" id="kunoichi"></a>
					</td>
				</tr>
				<tr>
					<td>
                        <a rel="classdesc" title="It wields a Crossbow as main weapon and automatically starts with its awakened weapon, the Longbow.<br><br><img src='img/classes/archer_diag.png' style='box-shadow: none' />"><img src="img/classes/archer.png" alt="archer" id="archer"></a>
                    </td>
                </tr>
                <tr>
					<td>
                        <a rel="classdesc" title="A class of skilled hunters with unparalleled precision. Rangers drive enemies away with rains of penetrating arrows that neutralize them at a distance.<br><br><img src='img/classes/ranger_diag.png' style='box-shadow: none' />"><img src="img/classes/ranger.png" alt="ranger" id="ranger"></a>
					</td>
				</tr>
				<tr>
					<td>
                        <a rel="classdesc" title="The Musa is a swordsman specializing in zone attacks. With a lightning speed it will allow him to defeat his opponents instantly while avoiding the danger.<br><br><img src='img/classes/musa_diag.png' style='box-shadow: none' />"><img src="img/classes/musa.png" alt="musa" id="musa"></a>
                    </td>
                </tr>
                <tr>
					<td>
                        <a rel="classdesc" title="An elegant sweeper using a vast arsenal of skill to keep enemies on the ground.<br><br><img src='img/classes/maehwa_diag.png' style='box-shadow: none' />"><img src="img/classes/maehwa.png" alt="maehwa" id="maehwa"></a>
					</td>
				</tr>
				<tr>
					<td>
                        <a rel="classdesc" title="Confront your enemies with the strength of your sword: use your shield to protect yourself from your opponents or immobilize them to finish them off with a deadly blow.<br><br><img src='img/classes/warrior_diag.png' style='box-shadow: none' />"><img src="img/classes/warrior.png" alt="warrior" id="warrior"></a>
                    </td>
                </tr>
                <tr>
					<td>
                        <a rel="classdesc" title="Armed with sacred powers, she uses magic and steel to defeat enemies or heal and help her allies.<br><br><img src='img/classes/valkyrie_diag.png' style='box-shadow: none' />"><img src="img/classes/valkyrie.png" alt="valkyrie" id="valkyrie"></a>
					</td>
				</tr>
				<tr>
					<td>
                        <a rel="classdesc" title="A destructive berserker armed with double-edged axes. With their attacks, the berserkers shake the earth and eliminate the surrounding enemies.<br><br><img src='img/classes/berserker_diag.png' style='box-shadow: none' />"><img src="img/classes/berserker.png" alt="berserker" id="berserker"></a>
					</td>
				</tr>
				<tr>
					<td>
                        <a rel="classdesc" title="The tamer can make implacable combinations of attacks or eliminate single enemies, borrowing divine forces.<br><br><img src='img/classes/tamer_diag.png' style='box-shadow: none' />"><img src="img/classes/tamer.png" alt="tamer" id="tamer"></a>
					</td>
				</tr>
				<tr>
					<td>
                        <a rel="classdesc" title="Master the occult arts with skill. Witches can cast many dark magic spells to win their enemies regardless of distance.<br><br><img src='img/classes/sorceress_diag.png' style='box-shadow: none' />"><img src="img/classes/sorceress.png" alt="sorceress" id="sorceress"></a>
					</td>
				</tr>
                <tr>
					<td>
                        <a rel="classdesc" title="With strong notions of black magic, the Darkblade performs heavy and deadly attacks with his majestic swordfish.<br><br><img src='img/classes/dark-knight_diag.png' style='box-shadow: none' />"><img src="img/classes/dark-knight.png" alt="dark-knight" id="dark-knight"></a>
					</td>
				</tr>
				<tr>
					<td>
                        <a rel="classdesc" title="The Lahn are martial artists: they are fighting with the Crescent Pendulum and can swiftly move great distances in the air.<br><br><img src='img/classes/lahn_diag.png' style='box-shadow: none' />"><img src="img/classes/lahn.png" alt="lahn" id="lahn"></a>
					</td>
				</tr>
				<tr>
					<td>
                        <a rel="classdesc" title="The Shai class is completely unique class in BDO and is the only full support class. They do reduced damage in PVP and have far less skills than other classes but have healing skills and buff/debuff skills.<br><br><img src='img/classes/shai_diag.png' style='box-shadow: none' />"><img src="img/classes/shai.png" alt="shai" id="shai"></a>
					</td>
				</tr>
			</table>
			<p>They are not all like the musa and the maehwa, that is to say that casiment the waking arm only differs. The Berserk class is not the same for ladies. Below, a demonstration of the magician's class with his own waking arm, we will limit ourselves to a combat demo:</p>
			<iframe width="560" height="315" src="https://www.youtube.com/embed/M2qmPbQRnrY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		</li>
		<li>
			<h3>CONCLUDE</h3>
			<p>An exceptional game, which can also make you put real money to facilitate certain tasks, saving time. An experience to live at least up to level 60-61. Very relevant ideas have personally forced me to stay online! </p>
		</li>
	</ol>
</div>
<!-- END  PAGE ABOUT BDO -->