<!-- Page d'ajout d'un article -->
<h2><i class="fas fa-pen-nib"></i> Add Post</h2>

<!-- Affichage de retour messages -->
<?php if($successMessage): ?>
    <p><?php printSuc($successMessage); ?></p>
<?php endif; ?>

<?php if($errorMessage): ?>
    <p><?php printEach($errorMessage); ?></p>
<?php endif; ?>

<!-- PAGE ADMIN ADD POST -->
<form class="my-form" action="" method="POST" enctype="multipart/form-data">
    <fieldset>
        <legend><i class="fa fa-check"></i> Characteristics (Please insert images in jpg/jpeg)</legend>
        <ul>
            <li>
                <label for="title">Title :</label>
                <input id="title" type="text" name="title">
            </li>
            <li>
                <label for="picture">Image :</label>
                <input id="picture" type="file" name="picture">
            </li>
            <li>
                <label class="textarea" for="contents">Contents :</label>
                <textarea id="contents" name="contents" rows="8"></textarea>
            </li>
            <li>
                <label for="memberId">Admin :</label>
                <select id="memberId" type="text" name="memberId">
                    <option value="1">sx77</option>
                </select>
            </li> 
            <li>
                <label for="categoryId">Category :</label>
                <select id="categoryId" type="text" name="categoryId">
                    <option value="1">Black Desert Online</option>
                    <option value="2">Enhancing</option>
                    <option value="3">Event</option>
                    <option value="4">Tournament</option>
                    <option value="5">MMORPG</option>
                    <option value="6">Zenith Kings</option>
                    <option value="7">Video Games</option>
                </select>
            </li> 
        </ul>
    </fieldset>
    <ul>
        <li>
            <input class="btn-send" type="submit" name="addPost" value="Add">
            <a class="btn-cancel" href="admin_posts.php">Cancel</a>
        </li>
    </ul>
</form>
<!-- END PAGE ADMIN ADD POST -->