<!-- Page d'administration -->

<!-- Page d'administration du site -->
<h2><i class="fa fa-cogs"></i> Admin</h2>

<!-- ADMIN PANEL PAGE -->
<div class="admin-panel">
    <a class="admin-btn" href="admin_posts.php">POSTS</a>
    <a class="admin-btn" href="admin_members.php">MEMBERS INFOS</a>
    <a class="admin-btn" href="admin_wars.php">WARS</a>
    <a class="admin-btn" href="admin_products.php">PRODUCTS</a>    
</div>
<!-- END ADMIN PANEL PAGE -->