<!-- Page d'ajout d'un match -->
<h2><i class="fas fa-fist-raised"></i> Add War</h2>

<!-- Affichage de retour messages -->
<?php if($successMessage): ?>
    <p><?php printSuc($successMessage); ?></p>
<?php endif; ?>

<?php if($errorMessage): ?>
    <p><?php printEach($errorMessage); ?></p>
<?php endif; ?>

<!-- PAGE ADMIN ADD WAR -->

<form class="my-form" action="" method="POST" enctype="multipart/form-data">
    <fieldset>
        <legend><i class="fa fa-check"></i> Characteristics (plz use logo in jpg, 60x60 pixels and same name as guild) </legend>
        <ul>
            <li>
                <label for="us">Us :</label>
                <input id="us" type="text" name="us">
            </li>
            <li>
                <label class="addlogo" for="addlogo">Our logo :</label>
                <input id="uslogo" type="file" name="usLogo">
            </li>
        </ul>
        <ul>
            <li>
                <label for="opponent">Opponent :</label>
                <input id="opponent" type="text" name="opponent">
            </li>
            <li>
                <label class="addlogo" for="addlogo">Opponent logo :</label>
                <input id="opponentlogo" type="file" name="opponentLogo">
            </li>
        </ul>
        <ul>
            <li>
                <label for="day">Day :</label>
                <select id="day" name="day" class="lvl">
                    <option value="Defaut">Quel jour..</option>
                    <option value="Dimanche">Dimanche</option>
					<option value="Lundi">Lundi</option>
					<option value="Mardi">Mardi</option>
					<option value="Mercredi">Mercredi</option>
					<option value="Jeudi">Jeudi</option>
					<option value="Vendredi">Vendredi</option>
					<option value="Samedi">Samedi</option>
                </select>
            </li> 
        </ul>
        <ul>
            <li>
                <label for="node">Node :</label>
                <select id="node" name="node" class="lvl">
                    <option value="Defaut">Quel géopoint..</option>                    
                    <option value="Balenos">Balenos</option>
                    <option value="Serendia">Serendia</option>
                    <option value="Mediah">Mediah</option>
                    <option value="Valencia">Valencia</option>
                    <option value="Calpheon">Calpheon</option>
                </select>
            </li> 
        </ul>
        <ul>
            <li>
                <label for="tier">Tier :</label>
                <select id="tier" name="tier" class="lvl">
                    <option value="Defaut">Quel cap ap/dp..</option>
                    <option value="Tier 1 easy">Tier 1 easy</option>
					<option value="Tier 1 middle">Tier 1 middle</option>
					<option value="Tier 1 hard">Tier 1 hard</option>
					<option value="Tier 2">Tier 2</option>
					<option value="Tier 3">Tier 3</option>
                    <option value="Tier 4">Tier 4</option>
                </select>
            </li> 
        </ul>
        <ul>
            <li>
                <label for="score">Score :</label>
                <input id="score" type="text" name="score" value="1 - 0 par exemple">
            </li> 
        </ul>
    </fieldset>
    <ul>
        <li>
            <input class="btn-send" type="submit" name="addWar" value="Add">
            <a class="btn-cancel" href="admin_wars.php">Cancel</a>
        </li>
    </ul>
</form>
<!-- END PAGE ADMIN ADD WAR -->