<!-- Page de contact de la guilde -->
<h2><i class="far fa-id-card"></i> Contact</h2>

<!-- PAGE CONTACT -->
<section id="contact">
    <p>You could also come to us on our discord channel! <a href="https://discord.gg/mwK6ZMG"><i class="fab fa-discord"></i> here</a></p>
</section>

<form class="my-form" action="mailto:zenith.kings77@gmail.com" method="POST" target="_blank">
    <fieldset>
        <legend><i class="far fa-envelope"></i> Send us a Message</legend>
        <ul>
            <li>
                <label for="name">Name :</label>
                <input id="name" type="text" name="name" placeholder="Enter your Name">
            </li>
            <li>
                <label for="email">E-mail :</label>
                <input id="email" type="email" name="email" placeholder="E-mail Required">
            </li>
            <li>
                <label for="message">Message :</label>
                <textarea id="message" type="textarea" name="message" placeholder="Your Message"></textarea>
            </li>
        </ul>
    </fieldset>

    <ul>
        <li>
            <input class="btn-send" type="submit" name="contact" value="Send message!">            
        </li>
    </ul>
</form>
<!-- END PAGE CONTACT -->