<!-- Page de liens intéressants sur ce jeu -->
<h2><i class="fas fa-link"></i> Links</h2>

<!-- PAGE LINKS -->
<section id="glinks">
    <article>
		<a href="https://www.world.blackdesertm.com/" target="_blank"><h4> BDO mobil</h4></a>
		<p>Black Desert Mobile will soon be available on iOS and Android. Stay tuned for more information...</p>
	</article>
	<article>
		<a href="https://bdoplanner.com/" target="_blank"><h4> BDOplanner</h4></a>
		<p>A short online build maker in order to check all gears and others..</p>
	</article>
	<article>
		<a href="https://www.invenglobal.com/blackdesertonline" target="_blank"><h4> InvenGlobal</h4></a>
		<p>If you need to know about bdo lastest news from Korea.</p>
	</article>
	<article>
		<a href="https://bddatabase.net/" target="_blank"><h4> BDDatabase</h4></a>
		<p>Very interesting website: world bosses timer, breed horse calculator, gears calculator & to compare, knowledge informations, and popular skills builds.</p>
	</article>
	<article>
		<a href="http://urzasarchives.com/bdo/wbtbdo/" target="_blank"><h4> Urzas Archives</h4></a>
		<p>World boss timer for all player in the world, check your region first!</p>
	</article>
	<article>
		<a href="http://www.somethinglovely.net/bdo/" target="_blank"><h4> Something Lovely</h4></a>
		<p>Usefull website: its all about trade, make crates to reach more levels to sell more and more things you craft with your own workers.. its also about breeding horses, and maybe one day awakened itself... You must find good idea on them map tool, all nodes and mineral resources are into..</p>
	</article>
	<article>
		<a href="http://i.imgur.com/yiW3n3c.jpg" target="_blank"><h4> Knowledge for noobs in enhancement</h4></a>
		<p>You will learned how to make filstack in order to cap your gears to a full max power.</p>
	</article>
</section>
<!-- END PAGE LINKS -->