<!-- Page de notre stream si éventuellement il y a -->
<h2><i class="fab fa-twitch"></i> Stream</h2>

<!-- PAGE STREAM -->
<section id="stream">
	<article>
		<a href="https://player.twitch.tv/?channel=zenith_kings"><img src="./img/zk twitch stream.png" alt="zk twitch logo from placeit.net"></a>
		<iframe src="https://player.twitch.tv/?channel=zenith_kings" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>		
	</article>
</section>
<!-- END PAGE STREAM -->