<!-- Page de mes wallpapers en 1920x1080 -->
<h2><i class="fas fa-desktop"></i> Wallpapers</h2>

<!-- PAGE WALLPAPERS -->
<section class="wlinks">
  <ul>
    <li>
      <a href="./img/wallpapers/zk01.jpg" target="_blank"> wallpaper 1: Desert Oger Laytenn</a>
      <a href="./img/wallpapers/zk02.jpg" target="_blank"> wallpaper 2: Overview Guild Page</a>
      <a href="./img/wallpapers/zk03.jpg" target="_blank"> wallpaper 3: Arduanatt Pegasus</a>
    </li>    
  </ul>
</section>

<section class="flexslider">    
	<ul class="slides">
        <li>
          <img src="./img/wallpapers/zk01.jpg" alt="Wallpaper zk01" title="Desert Oger Laytenn" />
        </li>
        <li>
          <img src="./img/wallpapers/zk02.jpg" alt="Wallpaper zk02" title="Overview Guild Page" />
        </li>
        <li>
          <img src="./img/wallpapers/zk03.jpg" alt="Wallpaper zk03" title="Arduanatt Pegasus" />
        </li>
	</ul>
</section>
<!-- END PAGE WALLPAPERS -->