<!-- FOOTER COMMUN -->
    <footer>
        
        <div class="foot-left">
            <div class="about-us">
                <h3>ABOUT US</h3>
                <a href="https://discord.gg/mwK6ZMG"><i class="fab fa-discord"></i> Discord</a>
                <a href="https://www.youtube.com/channel/UCcOm0LrFir-LrOqchppJzcg"><i class="fab fa-youtube"></i> YouTube</a>
                <a href="https://steamcommunity.com/groups/zenith_kings"><i class="fab fa-steam-symbol"></i> Steam</a>
            </div>
        </div>
        <div class="foot-center">
            <!--<a href="#" class="logoZ"></a>-->
            <a href=""><h1>ZENITH KINGS</h1></a>
            <!--<img src="img/3wa.png" style="max-width: 50px" />-->
            <div class="ends2">
                <a href="mailto:zenith.kings77@gmail.com" rel="cc:morePermissions">zenith.kings77@gmail.com</a>. La maquette a été réalisée par <a href="mailto:altman_mike@yahoo.fr">ALTMAN Michaël</a>
            </div>
        </div>
        <div class="foot-right" >
            <a href="https://www.blackdesertonline.com" class="logoBDO" target="_blank"></a>
        </div>
    </footer>

  
</body>
</html>